### ISSUE TITLE
Component: Navigation Dots

### ISSUE THREAD

**Issue by ZakkMan** [CotripperPlatform/CoTrip#11]
![Screen Shot 2019-12-04 at 10 37 57 AM](https://user-images.githubusercontent.com/4991553/70156588-29bc7e80-1682-11ea-90e4-975fa368cb5f.png)

The Navigation Dots component should take a number of dots in the list, the currently active dot, and a callback for when a dot is clicked. 

Properties:
* `active`: boolean
* `onStatusChange`: callback

Depending on the step of the user creation, a particular dots `active` property will become true which will change the color. Call back will go to that particular step of the signup.

**Comment by bmillsmc** [comment]
Closing, use Carousel Dot Component
