### ISSUE TITLE
Component: Nav Icons

### ISSUE THREAD

**Issue by wchrapcynski** [CotripperPlatform/CoTrip#12]
<img width="213" alt="nav-icons" src="https://user-images.githubusercontent.com/55462150/70169952-d0f8e000-1699-11ea-8d9f-255b28a1293c.png">

Nav Icons go to different sections/popups:
1: Search
2: Chat/Message
3: Profile

Properties:
* `image`: string
* `active`: boolean
* `onStatusChange`: callback

If `active` is set to true, that component should display.

**Comment by ZakkMan** [comment]
These are in  #74, so I'm going to close it
