### ISSUE TITLE
Component: Banner Issue

### ISSUE THREAD

**Issue by shelbyvjacobs** [CotripperPlatform/CoTrip#149]
`<Banner />` is the parent component of the following card components. These are grouped together because of their similar format/styling/content. Use {props.children} to pass these in to `<Banner />`.

The `Banner` component should have the prop:
* `path` : the path or url to the background image.

Using JSX and the special `props.children` there are three types of banners that should be made from the `Banner` component:
### Text Banner
A banner with just a heading.
![Screen Shot 2019-12-09 at 2 23 12 PM](https://user-images.githubusercontent.com/53311285/70465675-7394d280-1a8f-11ea-8d7a-91709858c5c0.png)
![Screen Shot 2019-12-09 at 2 42 28 PM](https://user-images.githubusercontent.com/53311285/70466911-3716a600-1a92-11ea-8f2c-e88349d8c344.png)

### Input Banner
A banner that has a search bar #23 and a heading.

![image](https://user-images.githubusercontent.com/53311285/70465621-54964080-1a8f-11ea-85aa-7d1d0d676a31.png)
![Screen Shot 2019-12-09 at 2 39 13 PM](https://user-images.githubusercontent.com/53311285/70466732-cf605b00-1a91-11ea-9242-6c65e419783f.png)
![Screen Shot 2019-12-09 at 2 40 39 PM](https://user-images.githubusercontent.com/53311285/70466782-ebfc9300-1a91-11ea-8f2d-48e2e23900a6.png)
![Screen Shot 2019-12-09 at 2 41 37 PM](https://user-images.githubusercontent.com/53311285/70466841-0b93bb80-1a92-11ea-975d-7ce81896fee2.png)
![Screen Shot 2019-12-09 at 2 42 41 PM](https://user-images.githubusercontent.com/53311285/70466919-3d0c8700-1a92-11ea-913f-de4baee37a5b.png)
![Screen Shot 2019-12-09 at 2 47 31 PM](https://user-images.githubusercontent.com/53311285/70467273-e2275f80-1a92-11ea-8c3a-58083a50c10a.png)
![Screen Shot 2019-12-09 at 2 47 22 PM](https://user-images.githubusercontent.com/53311285/70467280-e6537d00-1a92-11ea-8640-4243e22ef140.png)
![Screen Shot 2019-12-09 at 2 45 29 PM](https://user-images.githubusercontent.com/53311285/70467320-fa977a00-1a92-11ea-81ab-c49b8f58ec9c.png)

### Form Banner
A banner that has a heading, a search bar #23 and a follow pill #68 (PR: #113 ), so that users can peruse information and follow, join, or favorite at their leisure.
![Screen Shot 2019-12-09 at 2 26 15 PM](https://user-images.githubusercontent.com/53311285/70465855-e3a35880-1a8f-11ea-96ae-5cd3e5dd15b0.png)
![Screen Shot 2019-12-09 at 2 28 18 PM](https://user-images.githubusercontent.com/53311285/70465993-2b29e480-1a90-11ea-8e42-f94b4e253487.png)
![Screen Shot 2019-12-09 at 2 28 52 PM](https://user-images.githubusercontent.com/53311285/70466040-44329580-1a90-11ea-8920-3106d214dbaf.png)
![Screen Shot 2019-12-09 at 2 43 54 PM](https://user-images.githubusercontent.com/53311285/70467004-688f7180-1a92-11ea-9615-0e0d777abda4.png)
![Screen Shot 2019-12-09 at 2 44 04 PM](https://user-images.githubusercontent.com/53311285/70467012-6a593500-1a92-11ea-8f2d-76b105d078d1.png)

**Comment by bmillsmc** [comment]
Can we update the `Banner` component to handle this Banner as well?
![Screen Shot 2019-12-09 at 1 51 27 PM](https://user-images.githubusercontent.com/53311285/70463551-1860e100-1a8b-11ea-8fc1-58feafdbf2a6.png)

**Comment by cenwachukwu** [comment]
We could do that
