### ISSUE TITLE
Component: Button Issue

### ISSUE THREAD

**Issue by tissakhosla** [CotripperPlatform/CoTrip#16]
![image](https://user-images.githubusercontent.com/53238865/70267423-711f3980-176c-11ea-84b9-5843b0b8bf56.png)

![image](https://user-images.githubusercontent.com/53238865/70269902-4daabd80-1771-11ea-8f72-350f10c771fd.png)

![image](https://user-images.githubusercontent.com/53238865/70270065-8e0a3b80-1771-11ea-9f69-44ec31fb0112.png)

Button Component.

Properties:

- ```text```: string
- ```onClick```: callback

**Comment by MobolanleAdebesin** [comment]
Button Component. 
Properties: 
- text: string 
- onClick: callback

**Comment by llucas314** [comment]
moved to #68
