### ISSUE TITLE
Component: Topic Card

### ISSUE THREAD

**Issue by tissakhosla** [CotripperPlatform/CoTrip#17]
![image](https://user-images.githubusercontent.com/53238865/70271623-c2cbc200-1774-11ea-92aa-01c5ad673275.png)

Topic Card Component:

Properties: 
- `text`: string 
- `favorited`: boolean 
- `onStatusChange`: callback
If active, is set to true, the text color should be white, and the background should be purple. If active is set to false, the text should be white and the background should be pink. 
If favorited is true, the heart icon should be present. If favorited is false, the heart icon should not be present.

**Comment by llucas314** [comment]
Moved to https://github.com/CotripperPlatform/CoTrip/issues/37
