### ISSUE TITLE
Component: GroupCard Issue

### ISSUE THREAD

**Issue by bmillsmc** [CotripperPlatform/CoTrip#176]
The `GroupCard` component is a child of the `Card` component #146. It should have five props:
* `groupName`: the name of the group being displayed
* `memberNumber`: an integer for the amount of people in the group
* `location`: city or area location of the group
* `state`: the state that the group is in, optional
* `mixedLocations`: a boolean that if `true` displays mixed locations instead of a city and state

### Examples
<img width="200" alt="Screen Shot 2019-12-10 at 11 28 55 AM" src="https://user-images.githubusercontent.com/55462909/70548467-90d5a980-1b40-11ea-9e33-067321be4ab7.png">
<img width="200" alt="Screen Shot 2019-12-10 at 11 29 10 AM" src="https://user-images.githubusercontent.com/55462909/70548473-9501c700-1b40-11ea-83da-d848bda8200a.png">
<img width="200" alt="Screen Shot 2019-12-10 at 11 29 19 AM" src="https://user-images.githubusercontent.com/55462909/70548478-97fcb780-1b40-11ea-8015-244a1c25b163.png">
<img width="200" alt="Screen Shot 2019-12-10 at 11 29 49 AM" src="https://user-images.githubusercontent.com/55462909/70548490-9df29880-1b40-11ea-98f8-e1cc5cc54374.png">

**Comment by shelbyvjacobs** [comment]
See Issue #39 and PR #156

**Comment by caioingber** [comment]
Bug in #350 resolved, component complete - closing
