### ISSUE TITLE
Component: UpcomingTrips Issue

### ISSUE THREAD

**Issue by bmillsmc** [CotripperPlatform/CoTrip#178]
The `UpcomingTrips` component is a child of the `Card` component #146. It should have four props:
* `location`: the location of the trip
* `date`: a string containing a month name and a year like so "MONTH 0000"
* `generalInfo`: an array of string that contain general information on the trip
* `url`: a url for linking to the related trip page

Use the `TripCard` component #175 with this.

### Example
<img width="300" alt="Screen Shot 2019-12-10 at 11 47 35 AM" src="https://user-images.githubusercontent.com/55462909/70549859-e448f700-1b42-11ea-981c-2ed52af0be94.png">

**Comment by shelbyvjacobs** [comment]
I'm working on this in Issue #140 and PR #180.
