### ISSUE TITLE
Component: Footer Issue

### ISSUE THREAD

**Issue by tissakhosla** [CotripperPlatform/CoTrip#18]
![image](https://user-images.githubusercontent.com/53238865/70267666-e559dd00-176c-11ea-9af0-e91716778e60.png)

These are links for the footer. Some are internal and some are external. 

If an external link, it will open in a new page/tab. 

```
position: absolute;
left: 0%;
right: 0%;
top: 100%;
bottom: -100%;
height: 63px;

background: #FFCB08;
transform: matrix(1, 0, 0, -1, 0, 0);
```

**Comment by wchrapcynski** [comment]
These are links for the footer. Some are internal and some are external. 

Properties:
* `text`: string
* `link`: string
* `onStatusChange`: callback

If an external link, it will open in a new page/tab. Otherwise it will have a callback for loading that component.

**Comment by ZakkMan** [comment]
@tissakhosla Do we need those properties? We'll probably just render the `<Footer />` component without any properties.
