### ISSUE TITLE
Component: Input Type Submit

### ISSUE THREAD

**Issue by tissakhosla** [CotripperPlatform/CoTrip#19]
![image](https://user-images.githubusercontent.com/53238865/70268288-22729f00-176e-11ea-941e-dd1e90442477.png)

![image](https://user-images.githubusercontent.com/53238865/70269297-1b4c9080-1770-11ea-9619-c524d893f0cc.png)

![image](https://user-images.githubusercontent.com/53238865/70269373-3c14e600-1770-11ea-9a2a-cc1fb98ffef0.png)

![image](https://user-images.githubusercontent.com/53238865/70269445-6666a380-1770-11ea-820d-a09bfd57c723.png)

![image](https://user-images.githubusercontent.com/53238865/70269491-7ed6be00-1770-11ea-9fa8-f8820afddf3c.png)

![image](https://user-images.githubusercontent.com/53238865/70269527-94e47e80-1770-11ea-870a-5d14b1c031c4.png)

**Comment by TylerEikenberg** [comment]
Closed, issue isn't specific enough, these components have their own issues.
