### ISSUE TITLE
Component: Pill Issue

### ISSUE THREAD

**Issue by ZakkMan** [CotripperPlatform/CoTrip#2]
![Screen Shot 2019-12-04 at 9 27 50 AM](https://user-images.githubusercontent.com/4991553/70150703-6b482c00-1678-11ea-9005-9b663bc3399b.png)
<img width="232" alt="Screen Shot 2019-12-06 at 2 46 58 PM" src="https://user-images.githubusercontent.com/55462909/70351639-61b8f280-1837-11ea-9d54-c1757661704c.png">
<img width="252" alt="Screen Shot 2019-12-06 at 2 48 14 PM" src="https://user-images.githubusercontent.com/55462909/70351679-76958600-1837-11ea-934d-c8f2272dfd38.png">

Pill Component.

Properties:
* `text`: string
* `active`: boolean
* `onStatusChange`: callback
* `iconPath`: String
* `iconActive`: boolean
* `iconOffset`: boolean

If `active` is set to true, the text color should be white and the background should be pink. If `active` is set to false, the text should be black and the background should be white.

The `onStatusChange` callback should be called after the status (i.e `active`) property is changed.

If `iconActive` is `true` then an icon should displayed on the right side, using `iconPath`, like the second image. If `iconOffset` is true then the icon should be offset towards the top of the pill like the third image. 

This should have a hover effect so that the background turns a very light pink when the user hovers over it.

**Comment by joshseven** [comment]
Duplicate component that will be covered in component buttons
