### ISSUE TITLE
Component: Simple Post Issue

### ISSUE THREAD

**Issue by tissakhosla** [CotripperPlatform/CoTrip#21]
![image](https://user-images.githubusercontent.com/53238865/70268532-a88ee580-176e-11ea-8d38-da6010fb84d7.png)

![image](https://user-images.githubusercontent.com/53238865/70269123-bf820780-176f-11ea-85c0-54a564e6f3c8.png)

**Comment by shelbyvjacobs** [comment]
Is this issue for the parent of the forum post & comment ( #85 ) components? The second screenshot looks exactly like the screenshot from #80 . I'm assuming that that screenshot is just an example of the post having topic pills?

**Comment by shelbyvjacobs** [comment]
I'm closing this issue. There is a duplicate issue ( #89 ) that has been assigned.
