### ISSUE TITLE
*bug* component - input text field - search directory

### ISSUE THREAD

**Issue by dynasty2** [CotripperPlatform/CoTrip#227]
![image](https://user-images.githubusercontent.com/53455521/70640371-da3dfb80-1c09-11ea-9ce5-5a535f95201f.png)

When the user enters text, the text shows behind the magnifying glass.  Can we make the text render further to the right or make the glass disappear after the user enters text?

**Comment by caioingber** [comment]
Closing this issue as I have confirmed this bug is no longer in place on the develop branch.
