### ISSUE TITLE
*bug* component - input text field - search trips

### ISSUE THREAD

**Issue by dynasty2** [CotripperPlatform/CoTrip#239]
![image](https://user-images.githubusercontent.com/53455521/70640909-bfb85200-1c0a-11ea-87df-530c9ff23899.png)

When the user enters text, the text shows behind the magnifying glass. Can we make the text render further to the right or make the glass disappear after the user enters text?

**Comment by TylerEikenberg** [comment]
Fixing now!

**Comment by TylerEikenberg** [comment]
Fixed!
