### ISSUE TITLE
Component: User Profile Pic

### ISSUE THREAD

**Issue by tissakhosla** [CotripperPlatform/CoTrip#24]
![image](https://user-images.githubusercontent.com/55366813/70270077-95314980-1771-11ea-9223-71504f1aa5e7.png)

![image](https://user-images.githubusercontent.com/55366813/70270090-9e221b00-1771-11ea-8938-3d209b63420d.png)

![image](https://user-images.githubusercontent.com/55366813/70270127-b5610880-1771-11ea-8405-661f47dd1954.png)

![image](https://user-images.githubusercontent.com/55366813/70270147-beea7080-1771-11ea-8447-1fd937b78ef8.png)

The profile pic component will take the properties of height and width, and a src for the image url/ background if we set it up as a div with the background set as an image. 

 - `height:` x px/vh/etc.
 - `width:` x px/vw/etc.
 - `url: ` source to image
 - `onClick: ` callback to open a menu/go to user profile

**Comment by wchrapcynski** [comment]
We may need to look into a a backend library for controlling the minimum and maximum image size that a user can upload. A separate one may be needed for creating the circle images from the uploaded profile picture.

**Comment by TylerEikenberg** [comment]
#86
