### ISSUE TITLE
bug - Trending hashtag card

### ISSUE THREAD

**Issue by dynasty2** [CotripperPlatform/CoTrip#242]
![image](https://user-images.githubusercontent.com/53455521/70642957-28ed9480-1c0e-11ea-93c0-21735533075e.png)

![image](https://user-images.githubusercontent.com/53455521/70643339-c648c880-1c0e-11ea-8db9-18f8fb605131.png)

Please add: 
key="uniqueNameOfYourChoosing" 
inside the div on line 19.

**Comment by TylerEikenberg** [comment]
Fixed! Added key to mapping.
