### ISSUE TITLE
Button Bug [needs a caliente  🔥 fix]

### ISSUE THREAD

**Issue by karenheyn** [CotripperPlatform/CoTrip#243]
The button components have a border that should  not be there 
<img width="244" alt="Screen Shot 2019-12-11 at 12 02 10 PM" src="https://user-images.githubusercontent.com/52424072/70643322-c1841480-1c0e-11ea-994b-1c87cc718b96.png">

on hover, the pink button becomes transparent, it should be a darker pink.
<img width="432" alt="Screen Shot 2019-12-11 at 12 02 38 PM" src="https://user-images.githubusercontent.com/52424072/70643379-dd87b600-1c0e-11ea-8c78-7aa1e4084701.png">

additionally, the focus property shouldn't show this border which appears red or blue depending on your browser settings: 
<img width="198" alt="Screen Shot 2019-12-11 at 12 04 18 PM" src="https://user-images.githubusercontent.com/52424072/70643454-08720a00-1c0f-11ea-9bae-d7e2a8d4144f.png">

all in all the button should look like this:
<img width="227" alt="Screen Shot 2019-12-11 at 12 05 17 PM" src="https://user-images.githubusercontent.com/52424072/70643502-19bb1680-1c0f-11ea-8973-1d721a18cf4d.png">

here is some sample CSS for the button: 
```

 button {
  border: none;
}
 button:hover {
  background-color: #df7362;
}
button:focus {
outline: none
}
```

**Comment by tissakhosla** [comment]
Will get merged with components-connections branch
