### ISSUE TITLE
bug - component - NavLinkDropdownMenu

### ISSUE THREAD

**Issue by dynasty2** [CotripperPlatform/CoTrip#246]
![image](https://user-images.githubusercontent.com/53455521/70644510-26406e80-1c11-11ea-8f44-6767de27556f.png)

![image](https://user-images.githubusercontent.com/53455521/70644516-2b9db900-1c11-11ea-9cbc-4109b0eb15d8.png)

please add:
key='uniqueKeyNameOfYourChoosing'
in Link.

**Comment by bhearn7** [comment]
bug found by Ashley

added key={li.text} for Noah/Lorenzo's tests to pass whenever ".map()" is used

**Comment by llucas314** [comment]
The component throws an error when props aren't passed. Maybe you could put default props for just an empty array. Also, the key still needs updating.
