### ISSUE TITLE
Upcoming Events Card BUG Issue

### ISSUE THREAD

**Issue by shelbyvjacobs** [CotripperPlatform/CoTrip#251]
![Screen Shot 2019-12-11 at 3 15 10 PM](https://user-images.githubusercontent.com/53311285/70657124-42e8a080-1c29-11ea-8c2f-62a5cf3650c2.png)

I made this component, and it was approved and merged to develop. I think there is a hover effect that someone added to another component that has a className that doesn't fit our naming convention.

**Comment by shelbyvjacobs** [comment]
I believe the issue is specifically that someone tried to style the Link (react-router-dom) without using a className.

**Comment by TylerEikenberg** [comment]
fixed!
