### ISSUE TITLE
Comment Body Responsiveness Issue

### ISSUE THREAD

**Issue by shelbyvjacobs** [CotripperPlatform/CoTrip#270]
Please change any component that is a child of other components to be sized with rem. The `<CommentBody />` component is wrapped in another component, so using % won't work in this case, unfortunately. Thanks!

**Comment by caioingber** [comment]
@reisrael4 @colleenobrien3 Were y'all working on the comment? Just checking to see if this is already addressed

**Comment by colleenobrien3** [comment]
@caioingber @reisrael4 this was addressed by someone in the previous cohort
