### ISSUE TITLE
Condensed popup Navbar menu Issue

### ISSUE THREAD

**Issue by wchrapcynski** [CotripperPlatform/CoTrip#285]
This is the menu that will display when the burger icon is clicked. The burger icon is displayed when the website not wide enough to show the entire main menu. There is nothing in the mock designed for this currently. @ZakkMan Can you advise on how to proceed?

**Comment by ZakkMan** [comment]
@wchrapcynski Can you come up with a design, using the elements we have? We'll want a variation on the navlinks that we have, but in a takeover-style menu

**Comment by wchrapcynski** [comment]
I'm not entirely sure how well it will work out but I'll make an attempt.
