### ISSUE TITLE
Setup Hygen

### ISSUE THREAD

**Issue by ZakkMan** [CotripperPlatform/CoTrip#3]
We need Hygen set up so that all our components have a consistent file structure.

Every component should have:
* `Component.js` - for component definition
* `Component.css` - component styling
* `Component.test.js` - tests for the component
* `Component.stories.js` - for storybook integration

Hygen should create a new folder under `src/components/` with the component's name.

[Hygen Documentation](https://www.hygen.io/)

**Comment by clarknoah** [comment]
Also will need to add documentation on the readme in order to properly use HYGEN

**Comment by clarknoah** [comment]
# Hygen Setup 
To use Hygen with your project, you need to first install it globally using NPM:

> npm install hygen -g 

Once you have installed hygen, you will be able to utilize it within the `browser` directory. 

# Hygen Generators 
There are two generators available for hygen, the `component-class` generator, and the `component-const` generator

## `component-class` 
The `component-class` generator creates four files within the src/components/ directory and automatically builds for you the component folder, as well as the four files you need to get started on a component. 

This generator creates a React `class` component, with a few lifecycle boilerplate functions built-in. 

To run the generator for this component, run the following command FROM the `browser` directory (it will be the directory that contains the _template folder within it):
> hygen component-class new --name NameOfComponent

The `component-class` generator is used to create the following files: 
###  src/components/NameOfComponent/NameOfComponent.css
Creates CSS Boilerplate
```css
.NameOfComponent {

}
```
###  src/components/NameOfComponent/NameOfComponent.js
React Component
```javascript
import React, {Component} from 'react';
import "./NameOfComponent.css";


// Class Based React Component
class NameOfComponent extends Component{
  constructor(props){
    super(props);
    console.log(props);

    // Default CSS class to apply to the Component
    this.state = {
      classList: "NameOfComponent"
    };
  }


  // Runs after Component is loaded in the broswer
  componentDidMount(){}


  // Runs after a component has been updated
  componentDidUpdate(){}


  // Runs right before a component is removed from the DOM
  componentWillUnmount(){}

  render(){
    return(
      <div className={this.state.classList}>
        NameOfComponent
      </div>
    );
  }
}

export default NameOfComponent;
```
### src/components/NameOfComponent/NameOfComponent.stories.js
Storybook Boilerplate
```javascript
import React from 'react';
import { storiesOf } from '@storybook/react';

import NameOfComponent from './NameOfComponent';


storiesOf('NameOfComponent', module)
    .add('NameOfComponent', () =>{
      return <NameOfComponent />
    }
)
```
###  src/components/NameOfComponent/NameOfComponent.test.js
Enzyme Test Script
```javascript
import React from 'react'
import { shallow } from 'enzyme'

import NameOfComponent from './NameOfComponent.js'

// We will describe a block of tests
describe('NameOfComponent component', () => {
	// we will write one individual test
  it('should render as expected', () => {
    // Shallow rendering renders a component without rendering any of its children
    const component = shallow(<NameOfComponent />)
    // We create an assertion within the test that checks if our component renders our name prop
    // expect(component.contains('Your name')).toBe(true)
  })
})


```
## `component-const` 
The `component-const` generator creates four files within the src/components/ directory and automatically builds for you the component folder, as well as the four files you need to get started on a component. 

This generator creates a React `const` `function` component.  

To run generate this component, run the following command FROM the `browser`directory (it will be the directory that contains the _template folder within it):
> hygen component-const new --name NameOfComponent

The `component-class` generator is used to create the following files: 
###  src/components/NameOfComponent/NameOfComponent.css
Creates CSS Boilerplate
```css
.NameOfComponent {

}
```
###  src/components/NameOfComponent/NameOfComponent.js
React Component
```javascript

import React from 'react';
import "./NameOfComponent.css";

// Function based React Component
const NameOfComponent = (props) => {

  // Default Class to apply to Component
  let classList = `NameOfComponent`;


  return(
    <div className={classList}>
      NameOfComponent
    </div>
  );
}

export default NameOfComponent;
```
### src/components/NameOfComponent/NameOfComponent.stories.js
Storybook Boilerplate
```javascript
import React from 'react';
import { storiesOf } from '@storybook/react';

import NameOfComponent from './NameOfComponent';


storiesOf('NameOfComponent', module)
    .add('NameOfComponent', () =>{
      return <NameOfComponent />
    }
)
```
###  src/components/NameOfComponent/NameOfComponent.test.js
Enzyme Test Script
```javascript
import React from 'react'
import { shallow } from 'enzyme'

import NameOfComponent from './NameOfComponent.js'

// We will describe a block of tests
describe('NameOfComponent component', () => {
	// we will write one individual test
  it('should render as expected', () => {
    // Shallow rendering renders a component without rendering any of its children
    const component = shallow(<NameOfComponent />)
    // We create an assertion within the test that checks if our component renders our name prop
    // expect(component.contains('Your name')).toBe(true)
  })
})


```

**Comment by llucas314** [comment]
@clarknoah Here is a template of how the storybook stories need to be set up to incorporate all of the addons. Let me know if you have any problems. 

https://gist.github.com/llucas314/dc72ff7a73a77564304c6e4b47459688

**Comment by clarknoah** [comment]
Thanks Lorenzo, I've added it to the template
