### ISSUE TITLE
Component: Person Card 

### ISSUE THREAD

**Issue by MobolanleAdebesin** [CotripperPlatform/CoTrip#31]
![image](https://user-images.githubusercontent.com/53238865/70275178-99626480-177b-11ea-92d8-f6d6c9f3ae9b.png)
<img width="395" alt="Screen Shot 2019-12-06 at 2 21 06 PM" src="https://user-images.githubusercontent.com/55251251/70349884-a9d61600-1833-11ea-8948-53c51378f147.png">

The **Person Card** component will display the persons photo, location, and hashtags.

**Props**
- Users info (photo, name, location, hashtags).

**Comment by shelbyvjacobs** [comment]
This is the same as #134 , correct?

**Comment by shelbyvjacobs** [comment]
And #57 ?

**Comment by DallasLind** [comment]
Yes, I'm working off of #57, but the branch is accidentally named after #134
