### ISSUE TITLE
Group Card 

### ISSUE THREAD

**Issue by MobolanleAdebesin** [CotripperPlatform/CoTrip#32]
![image](https://user-images.githubusercontent.com/53238865/70275228-b0a15200-177b-11ea-99fa-5f8fbb0ec823.png)

Group Card Component 

Properties: 
- `text`: string 
- `location`: string 
- `# of members`: string

**Comment by llucas314** [comment]
Moved to https://github.com/CotripperPlatform/CoTrip/issues/39
