### ISSUE TITLE
Component: Posted Card

### ISSUE THREAD

**Issue by llucas314** [CotripperPlatform/CoTrip#38]
<img width="170" alt="Screen Shot 2019-12-05 at 8 45 05 PM" src="https://user-images.githubusercontent.com/42591694/70288619-2e775480-17a0-11ea-882f-4ddfee71c67c.png">

Posted Card Component:

Properties:
* `background-color`: #FB836F
* `border-radius`: 3px

* `name`: string
* `large`: boolean

`name` should be appended to "Posted by:"  and wrapped in a container with a `background-color`: rgba(106, 76, 147, 0.5)

* `font-family`: Open Sans
* `font-size` : 14px
* `align-text` : Left

If `large` is set to true, the height and width should be 248px and the text container should have a height of 29.31px, if false the height and width should be 220px and the text container should have a height of 26px.

This should have a hover effect so that the background turns a very light pink when the user hovers over it.

**Comment by joshseven** [comment]
Issue already being worked on in another issue

**Comment by joshseven** [comment]
Component already being worked on #98
