### ISSUE TITLE
Component: Info Card Issue

### ISSUE THREAD

**Issue by llucas314** [CotripperPlatform/CoTrip#39]
<img width="193" alt="Screen Shot 2019-12-05 at 9 17 45 PM" src="https://user-images.githubusercontent.com/42591694/70290075-c8d99700-17a4-11ea-9aa3-83c085c9cb1d.png">

Info Card Component:

Properties:

* `group`: {
    `name`: string,
    `members`: int,
    `location`: string,
    `state`: string
}

* `trip`: {
    `location`: string,
    `month`: string,
    `year`: int
}

If the `group` object is passed as a prop, display the objects with the following css:

- `width`: 220px
- `height`: 150px
- `border-radius`: 3px
- `background-color`: #FB836F
- `filter`: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));

`name`: 

- Font Family: Reem Kufi (https://fonts.google.com/specimen/Reem+Kufi)
- Font Style: Regular
- Font Size: 24px
- Line Height: 36px
- Line Height: 100%
- Align: Left
- Vertical Align: Top
- Color: #FFFFFF

`members`:

- Font Family: Reem Kufi (https://fonts.google.com/specimen/Reem+Kufi)
- Font Style: Regular
- Font Size: 14px
- Line Height: 21px
- Line Height: 100%
- Align: Left
- Vertical Align: Top
- Color: #FFFFFF

`location` & `state`:

- Font Family: Reem Kufi (https://fonts.google.com/specimen/Reem+Kufi)
- Font Style: Regular
- Font Size: 14px
- Line Height: 21px
- Line Height: 100%
- Align: Right
- Vertical Align: Top
- Color: #FFFFFF

If the `trip` object is passed as a prop, display the objects with the following css:

- `width`: 218px
- `height`: 145px
- `border-radius`: 3px
- `background-color`: rgba(196, 196, 196, 0.25)

`location`:

- Font Family: Reem Kufi (https://fonts.google.com/specimen/Reem+Kufi)
- Font Style: Regular
- Font Size: 24px
- Line Height: 36px
- Line Height: 100%
- Align: Center
- Vertical Align: Top
- Color: #FFFFFF

`month` & `year`:

- Font Family: Reem Kufi (https://fonts.google.com/specimen/Reem+Kufi)
- Font Style: Regular
- Font Size: 18px
- Line Height: 27px
- Line Height: 100%
- Align: Center
- Vertical Align: Top
- Color: #FAFAFA

**Comment by bmillsmc** [comment]
Moved this component into two issues at #175 and #176
