### ISSUE TITLE
As a user I would like to see the profiles of other users

### ISSUE THREAD

**Issue by Underwaterr** [CotripperPlatform/CoTrip#423]

**Comment by MilesHamilton** [comment]
![screencapture-localhost-3000-community-explore-people-1593542519673](https://user-images.githubusercontent.com/46730797/86164679-2423fb80-bae0-11ea-9b6f-0494e4ac0b96.png)

**Comment by MilesHamilton** [comment]
![screencapture-localhost-3000-community-explore-people-1593542744185](https://user-images.githubusercontent.com/46730797/86164887-80871b00-bae0-11ea-9e28-2ba522bc1dd3.png)

made it possible for a user to see all other users from the data in the /profile path to the /community/explore-people path on the  front end with random images as placeholders for each field
