### ISSUE TITLE
Component: Scrapbook Location Cards

### ISSUE THREAD

**Issue by TylerEikenberg** [CotripperPlatform/CoTrip#50]
<img width="263" alt="Screen Shot 2019-12-06 at 11 44 07 AM" src="https://user-images.githubusercontent.com/55251251/70347759-3fbb7200-182f-11ea-9e0d-eb0e19ead34e.png">

Props:
- Image source
- Posted by

Styles: 
- ```Height/Width```: **250px**
- ```Color for 'posted by' banner```: **6A4C93**

**Comment by joshseven** [comment]
Item already being created in another issue #98.
