### ISSUE TITLE
Component: Welcome Header

### ISSUE THREAD

**Issue by TylerEikenberg** [CotripperPlatform/CoTrip#52]
<img width="1434" alt="Screen Shot 2019-12-06 at 12 04 08 PM" src="https://user-images.githubusercontent.com/55251251/70348228-44345a80-1830-11ea-81a0-b985e9b48461.png">

**Props:**
- Users first name

**Comment by ZakkMan** [comment]
This could probably be merged with #71 and #97

**Comment by TylerEikenberg** [comment]
Merging this component with #71 and #97
