### ISSUE TITLE
Components: Nav Link & Nav Link Dropdown Menu

### ISSUE THREAD

**Issue by DallasLind** [CotripperPlatform/CoTrip#59]
NOTE: images not to scale

![image](https://user-images.githubusercontent.com/54913865/70455246-f0b54d00-1a79-11ea-8af5-69b91fd633cf.png)
![image](https://user-images.githubusercontent.com/54752666/70348685-37643680-1831-11ea-8375-75f0e42f0a59.png)

**Comment by bhearn7** [comment]
NEED to fix Redirect once routes are made
NEED to fix any styling issues once this is inserted into the NavBar
