### ISSUE TITLE
Component: Previous Trips/Hashtags Card

### ISSUE THREAD

**Issue by TylerEikenberg** [CotripperPlatform/CoTrip#60]
<img width="520" alt="Screen Shot 2019-12-06 at 11 55 21 AM" src="https://user-images.githubusercontent.com/55251251/70348509-d0468200-1830-11ea-8d93-f05e95b622d6.png">
<img width="369" alt="Screen Shot 2019-12-06 at 11 33 40 AM" src="https://user-images.githubusercontent.com/55251251/70348515-d2a8dc00-1830-11ea-9d9d-578832e1399a.png">

**Props**
- _Previous Trip_ or _Hashtag_ to determine which version is displayed.
- **IF props === Previous Trip**  
    -Props for array of names of previous trip locations
- **IF props === Hashtag**  
    -Props for array of hashtags (max length of 10)

Styles: 
- ```Height```: **265px**
- ```Width```: **505px**

- ```Background-Color```: **6A4C93**

**Comment by bmillsmc** [comment]
This component has been split into two separate issues at #171 and #172.
