### ISSUE TITLE
Get the tabs to route to their respective pages

### ISSUE THREAD

**Issue by dakom0** [CotripperPlatform/CoTrip#603]
**Describe the bug**
Clicking on the tabs do nothing.

1. Go to 'http://localhost:3000/directory/groups'
2. Click on 'My Groups/ My Friends'
3. No change

**Expected behavior**
Clicking on the tabs should route you to that page if you’re not already there.

![Screen Shot 2020-05-18 at 12 05 00 PM](https://user-images.githubusercontent.com/61025444/82240239-10458100-9908-11ea-9a2b-0c209a090c91.png)

**Comment by skut21x-ga** [comment]
@dakom0 I finished this
