### ISSUE TITLE
Component: Topic Pill Issue

### ISSUE THREAD

**Issue by cjohnston96** [CotripperPlatform/CoTrip#64]
<img width="183" alt="Screen Shot 2019-12-06 at 2 07 10 PM" src="https://user-images.githubusercontent.com/30026036/70348963-ca9d6c00-1831-11ea-893b-132f47991dd0.png">

Text inside of div possibly as **props**

**Comment by nickmckenney** [comment]
Working on Pill Atomic Component
 per #64

**Comment by nickmckenney** [comment]
This issue seems fixed. Worked on changing the props to pass down background color as well as text instead of using css
