### ISSUE TITLE
Draft a readme for the client

### ISSUE THREAD

**Issue by ZakkMan** [CotripperPlatform/CoTrip#7]
We currently just have the default readme from create-react-app. We need one that includes:

* Description/background
* Setup and installation instructions
* Background on the component library
* Documentation on the Hygen setup (#3)

**Comment by wchrapcynski** [comment]
@ZakkMan There is currently quite a bit in the readme already that I was thinking that I needed to do. Until we have the application built, I'm not sure what more I can add right now.

**Comment by ZakkMan** [comment]
@wchrapcynski Theres a first draft of the readme for the whole project - You can move some of that into the readme for the client if you think that's where it makes more sense. I think the biggest contribution here is instructions for everyone on getting this app up and running on their laptops. This documentation will change as the app gets built out. But we also need instructions on how to get it set up as it it

**Comment by wchrapcynski** [comment]
@ZakkMan Are you still changing the folder for the client from browser to client? You mentioned it yesterday. Since it's still browser, I'll call it that for now in the readme.

**Comment by clarknoah** [comment]
Bill, below this line is the documentation for hygen:
# Hygen Setup 
To use Hygen with your project, you need to first install it globally using NPM:

> npm install hygen -g 

Once you have installed hygen, you will be able to utilize it within the `client` directory. 

# Hygen Generators 
There are two generators available for hygen, the `component-class` generator, and the `component-const` generator

## `component-class` 
The `component-class` generator creates four files within the src/components/ directory and automatically builds for you the component folder, as well as the four files you need to get started on a component. 

This generator creates a React `class` component, with a few lifecycle boilerplate functions built-in. 

To run the generator for this component, run the following command FROM the `client` directory (it will be the directory that contains the _template folder within it):
> hygen component-class new --name NameOfComponent

The `component-class` generator is used to create the following files: 
###  src/components/NameOfComponent/NameOfComponent.css
Creates CSS Boilerplate
```css
.NameOfComponent {

}
```
###  src/components/NameOfComponent/NameOfComponent.js
React Component
```javascript
import React, {Component} from 'react';
import "./NameOfComponent.css";


// Class Based React Component
class NameOfComponent extends Component{
  constructor(props){
    super(props);
    console.log(props);

    // Default CSS class to apply to the Component
    this.state = {
      classList: "NameOfComponent"
    };
  }


  // Runs after Component is loaded in the broswer
  componentDidMount(){}


  // Runs after a component has been updated
  componentDidUpdate(){}


  // Runs right before a component is removed from the DOM
  componentWillUnmount(){}

  render(){
    return(
      <div className={this.state.classList}>
        NameOfComponent
      </div>
    );
  }
}

export default NameOfComponent;
```
### src/components/NameOfComponent/NameOfComponent.stories.js
Storybook Boilerplate
```javascript
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from "@storybook/addon-actions";
import { withKnobs, object } from "@storybook/addon-knobs/react";
import NameOfComponent from './NameOfComponent';

//Props to be changed with Knobs add on
export const topic = {
  text: "text",
  favorite: true,
  hashtag: true
};

// Functions to be used by component
export const actions = {
  onStatusChange: action("Status Change")
};


storiesOf('NameOfComponent', module)
// addDecorator and "Default" story are needed to generate story that can be modified by Knobs addon
  .addDecorator(withKnobs)
  .add("Default", () => (
    <Component topic={object("topic", { ...topic })} {...actions} />
  ))
// add component stories as ususal...
    .add('NameOfComponent', () =>{
      return <NameOfComponent />
    }
)

```
###  src/components/NameOfComponent/NameOfComponent.test.js
Enzyme Test Script
```javascript
import React from 'react'
import { shallow } from 'enzyme'

import NameOfComponent from './NameOfComponent.js'

// We will describe a block of tests
describe('NameOfComponent component', () => {
	// we will write one individual test
  it('should render as expected', () => {
    // Shallow rendering renders a component without rendering any of its children
    const component = shallow(<NameOfComponent />)
    // We create an assertion within the test that checks if our component renders our name prop
    // expect(component.contains('Your name')).toBe(true)
  })
})


```
## `component-const` 
The `component-const` generator creates four files within the src/components/ directory and automatically builds for you the component folder, as well as the four files you need to get started on a component. 

This generator creates a React `const` `function` component.  

To run generate this component, run the following command FROM the `client` directory (it will be the directory that contains the _template folder within it):
> hygen component-const new --name NameOfComponent

The `component-class` generator is used to create the following files: 
###  src/components/NameOfComponent/NameOfComponent.css
Creates CSS Boilerplate
```css
.NameOfComponent {

}
```
###  src/components/NameOfComponent/NameOfComponent.js
React Component
```javascript

import React from 'react';
import "./NameOfComponent.css";

// Function based React Component
const NameOfComponent = (props) => {

  // Default Class to apply to Component
  let classList = `NameOfComponent`;


  return(
    <div className={classList}>
      NameOfComponent
    </div>
  );
}

export default NameOfComponent;
```
### src/components/NameOfComponent/NameOfComponent.stories.js
Storybook Boilerplate
```javascript
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from "@storybook/addon-actions";
import { withKnobs, object } from "@storybook/addon-knobs/react";
import NameOfComponent from './NameOfComponent';

//Props to be changed with Knobs add on
export const topic = {
  text: "text",
  favorite: true,
  hashtag: true
};

// Functions to be used by component
export const actions = {
  onStatusChange: action("Status Change")
};


storiesOf('NameOfComponent', module)
// addDecorator and "Default" story are needed to generate story that can be modified by Knobs addon
  .addDecorator(withKnobs)
  .add("Default", () => (
    <Component topic={object("topic", { ...topic })} {...actions} />
  ))
// add component stories as ususal...
    .add('NameOfComponent', () =>{
      return <NameOfComponent />
    }
)

```
###  src/components/NameOfComponent/NameOfComponent.test.js
Enzyme Test Script
```javascript
import React from 'react'
import { shallow } from 'enzyme'

import NameOfComponent from './NameOfComponent.js'

// We will describe a block of tests
describe('NameOfComponent component', () => {
	// we will write one individual test
  it('should render as expected', () => {
    // Shallow rendering renders a component without rendering any of its children
    const component = shallow(<NameOfComponent />)
    // We create an assertion within the test that checks if our component renders our name prop
    // expect(component.contains('Your name')).toBe(true)
  })
})


```
