### ISSUE TITLE
Component: Molecular Pink Header Issue

### ISSUE THREAD

**Issue by torykling** [CotripperPlatform/CoTrip#71]
![image](https://user-images.githubusercontent.com/55210397/70350359-9ecfb580-1834-11ea-9fa3-2e6f297347f4.png)

Props:
-Title

Atom component: 
-Input Type Text

Locations: 
-Members Profile
-Forum Discover
-Directory People
-Directory Groups

```
/* cotripper_banner2-01 */


position: absolute;
width: 1440px;
height: 231px;
left: -2px;
top: 128px;

background: url(cotripper_banner2-01.png);
box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
```

**Comment by bmillsmc** [comment]
If you are on this issue please move to issue #164
