### ISSUE TITLE
Component: Icons

### ISSUE THREAD

**Issue by RaymondNwambuonwo** [CotripperPlatform/CoTrip#74]
![write](https://user-images.githubusercontent.com/54545904/70349487-cb82cd80-1832-11ea-8e46-7b2b9e68344a.png)

![arrow](https://user-images.githubusercontent.com/54545904/70349886-aa6eac80-1833-11ea-9acd-74adebd8f04e.png)
![Black fill heart](https://user-images.githubusercontent.com/54545904/70349887-aa6eac80-1833-11ea-9ab0-11b7206f93cb.png)
![Company Logo Icon](https://user-images.githubusercontent.com/54545904/70349888-aa6eac80-1833-11ea-84ff-4913668b971f.png)
![empy heart pink background](https://user-images.githubusercontent.com/54545904/70349889-aa6eac80-1833-11ea-9f1d-6923ca5c1bc1.png)
![Facebook](https://user-images.githubusercontent.com/54545904/70349890-aa6eac80-1833-11ea-8a78-e69f0f661dda.png)
![Instagram](https://user-images.githubusercontent.com/54545904/70349891-aa6eac80-1833-11ea-93e5-55ca2e241dbc.png)
![magnifying glass](https://user-images.githubusercontent.com/54545904/70349892-aa6eac80-1833-11ea-8e88-aebe6825a846.png)
![message bubble](https://user-images.githubusercontent.com/54545904/70349893-ab074300-1833-11ea-804c-3f1471071834.png)
![Pinterest ](https://user-images.githubusercontent.com/54545904/70349894-ab074300-1833-11ea-9df6-5336714bba9a.png)

`imagesource` = url
Location: Inbox
path: a link

**Comment by caioingber** [comment]
@ZakkMan @Underwaterr closing out this issue as icons have been incorporated into develop branch and there do not appear to be any other missing features.
