### ISSUE TITLE
Component: Button/Input Type Submit Component Issue

### ISSUE THREAD

**Issue by clarknoah** [CotripperPlatform/CoTrip#75]
<img width="297" alt="Screen Shot 2019-12-06 at 2 19 35 PM" src="https://user-images.githubusercontent.com/1622159/70350022-e6097680-1833-11ea-84aa-f536a2fc6022.png">

<img width="183" alt="Screen Shot 2019-12-06 at 2 17 59 PM" src="https://user-images.githubusercontent.com/1622159/70350041-ee61b180-1833-11ea-92a7-3fdaef3f4742.png">

<img width="287" alt="Screen Shot 2019-12-06 at 2 19 11 PM" src="https://user-images.githubusercontent.com/1622159/70350032-eb66c100-1833-11ea-82f9-fb7e39de6ece.png">

<img width="287" alt="Screen Shot 2019-12-06 at 2 19 21 PM" src="https://user-images.githubusercontent.com/1622159/70350027-e86bd080-1833-11ea-90cf-44bfbf213d8c.png">

- Location:
    - Onboarding
    - #PackingLight
    - Pretty much everywhere!
- Features
    - Clickable button that should allow the parent to run a function each time it is clicked
    - It could be button or input type submit
- Inputs
    - backgroundColor={
    - TextColor
- Internal Actions
    - Style correctly based on input properties
    - buttonClicked function which should execute the `this.props.clickedAction` function
- Outputs
    - Component should have clickedAction={parentFunctionClicked} which accepts an object from within the com

**Comment by karenheyn** [comment]
move to #168
