### ISSUE TITLE
Component: Book a trip 

### ISSUE THREAD

**Issue by karenheyn** [CotripperPlatform/CoTrip#76]
<img width="304" alt="Screen Shot 2019-12-06 at 11 41 11 AM" src="https://user-images.githubusercontent.com/52424072/70349655-274d5680-1833-11ea-9143-67f01b4a90aa.png">

css:
```
position: absolute;
width: 500px;
height: 275px;
left: 910px;
top: 556px;
```

props:
```trip card```

path:
```book a trip```

**Comment by sarahtsige** [comment]
@ZakkMan @Underwaterr    This component is in the component library and appears to be built as well.  Let me know if it needs anything else or if it's ok to close this issue.
