### ISSUE TITLE
Component: Interaction Card Issue

### ISSUE THREAD

**Issue by bmillsmc** [CotripperPlatform/CoTrip#77]
<img width="174" alt="Screen Shot 2019-12-06 at 12 07 24 PM" src="https://user-images.githubusercontent.com/55462909/70349072-09332680-1832-11ea-8548-d297db651964.png">

### Interaction Card Component

Properties:

- `connectFunc`: callback
- `messageFunc`: callback

`connectFunc` should be a function that when called sends a connect request to the appropriate user. `messageFunc` should, similarly, when called message the appropriate user.

**Comment by shelbyvjacobs** [comment]
Hey Ben! We don't have this in our list of card components. Would you like to include it?
