### ISSUE TITLE
Component: Slider Container Issue

### ISSUE THREAD

**Issue by stuvun** [CotripperPlatform/CoTrip#79]
**Location:** Hawaii 2020
**Image Slide Container:**
![slider](https://user-images.githubusercontent.com/55634628/70350085-09ccbc80-1834-11ea-8323-779e74a31498.png)

**Components:**
* Carousel Dot Component

**Props:**
* `location`

**Comment by shelbyvjacobs** [comment]
Is the slideCount the dots at the bottom? I'm about to make an issue for that as an atomic component, which we called Carousel Dots and I want to see if we can make it more consistent. 😄

**Comment by stuvun** [comment]
Oh yes it is, I just edited my issue to show that it's another component within this component.

**Comment by stuvun** [comment]
I'll change it to Carousel Dots

**Comment by shelbyvjacobs** [comment]
Cool! Thanks. The Carousel Dots atomic component is in **Issue #84**!

**Comment by clarknoah** [comment]
This can be considered a Molecular component that depends on the CarouselDots component
