### ISSUE TITLE
Component: Inbox Menu Issue

### ISSUE THREAD

**Issue by shelbyvjacobs** [CotripperPlatform/CoTrip#81]
![Screen Shot 2019-12-06 at 2 33 57 PM](https://user-images.githubusercontent.com/53311285/70350793-772d1d00-1835-11ea-9ef9-51e22e18d866.png)

Atoms:
Convo Block
Icon

**Comment by saralaffin** [comment]
@ZakkMan @Underwaterr I don't see the Inbox component anywhere.. should I keep digging, or re-open this issue?

**Comment by saralaffin** [comment]
Re-opened #22 instead of this one
