### ISSUE TITLE
Component: Image Card Issue

### ISSUE THREAD

**Issue by cenwachukwu** [CotripperPlatform/CoTrip#82]
## Image card:
![image](https://user-images.githubusercontent.com/55363613/70348328-7776e980-1830-11ea-9fd7-1a680e9e20ab.png)
An image card has the following specs:
*  url(4k-wallpaper-bay-beach-2521619.jpg);
* Text prop
~~`textLines`: Number~~

~~The `textLines` prop should define how many lines of text are on the image. For example, in the above image the number of lines would be 2, one for "May 2020", and one for "Hawaii"~~

**Comment by bmillsmc** [comment]
This has been moved to #175
