### ISSUE TITLE
Component: Carousel Dot Component Issue

### ISSUE THREAD

**Issue by clarknoah** [CotripperPlatform/CoTrip#84]
<img width="289" alt="Screen Shot 2019-12-06 at 2 37 29 PM" src="https://user-images.githubusercontent.com/1622159/70351048-0b977f80-1836-11ea-8670-de5dc559e1c8.png">

<img width="572" alt="Screen Shot 2019-12-06 at 2 38 11 PM" src="https://user-images.githubusercontent.com/1622159/70351057-13572400-1836-11ea-8816-ad23328bb051.png">

- Features
    - Component should have one dot highlighted and the others white
- Inputs
    - `numberOfDots`: number of inputDots
    - `currentLocation`: currentlyHighlightedPosition
    - `highlightedDotColor`: color for highlighted dot 
    - `notHighlightedDotColor`: color for circles not highlighted
    - `hasBorder`: boolean which will determine whether to have a border for the circle if unselected
- Internal Actions
    - On `componentDidUpdate()`
    - Check currentLocation prop and update pill accordingly
- Outputs
    - `onStatusChange`: callback

**Comment by shelbyvjacobs** [comment]
Also see **Issue #11** - Component: Navigation Dots

**Comment by caioingber** [comment]
This has been complete per notes above and closed PR #111
