### ISSUE TITLE
Component: Forum Comment 

### ISSUE THREAD

**Issue by cjohnston96** [CotripperPlatform/CoTrip#87]
<img width="620" alt="Screen Shot 2019-12-06 at 2 43 31 PM" src="https://user-images.githubusercontent.com/30026036/70351390-d4759e00-1836-11ea-8a38-971a117a3e59.png">

**(Molecular)**
- User Profile Pic/Name **(Component)**
- Forum Comment Body **(component)**
- Likes/replies **(props)**

**Comment by reisrael4** [comment]
This was moved over to a component just called "Comment" by @colleenobrien3.
