### ISSUE TITLE
Component: Navbar

### ISSUE THREAD

**Issue by cenwachukwu** [CotripperPlatform/CoTrip#88]
![image](https://user-images.githubusercontent.com/55363613/70351314-a728f000-1836-11ea-8b8a-2d6cb96b7454.png)
 
props: src for (logo, icons, profile picture), links ( to pages in the site)

**Comment by shelbyvjacobs** [comment]
Location:
- Global Nav
- Etc.
- Book A Trip
- Home: Old User
- Hawaii2020
- Members Profile
- Forum: Favorites
- Forum: search bar
- Forum: search results
- #PackingLight

**Comment by wchrapcynski** [comment]
All is currently looking good so far. The arrow (a pink and a purple version) on the menu needs to be added but that needs to be part of the NavLink component. @bhearn7, Can you look into that for your component? Feel free to talk to me about it. 

We are currently missing a menu component for the condensed version that pops up when using the burger icon. @ZakkMan This is something that isn't in the Mobile Mock. How should we proceed?
