### ISSUE TITLE
Component Molecular: Forum Post / Comment | Location Form group | Issue

### ISSUE THREAD

**Issue by nickmckenney** [CotripperPlatform/CoTrip#89]
<img width="626" alt="Screen Shot 2019-12-06 at 2 45 14 PM" src="https://user-images.githubusercontent.com/55772458/70351486-071f9680-1837-11ea-9da9-684fae188342.png">

--- Post {Component} ----

{Component: Profile Picture with User Name}
`Image`: file.png(Circle)
`User Name`: Name of User
{Component}

`Title`: "Post Title": String {Component}

`HashTags`: Text {Component}

`Date`: ex(Aug 19 6:00pm) {Component}

`PostText`: Text

`Likes/Comments` : Number and String {Component}

`Topic Pill`: String

`Like Button / Comment Button`: Button {Component}

--- Comment {component} ---

{Component: Profile Picture with User Name}
`Image`: file.png(Circle)
`User Name`: Name of User
{Component}

`Text`:String
`Date`: ex(Aug 19 6:00pm) {Component}

`Likes/Replies`: Number and String {Component}

CSS Information:
Fourm Post:
```
position: absolute;
left: 0%;
right: 0%;
top: 0%;
bottom: 47.48%;
background: #FAFAFA;
border: 1px solid rgba(37, 37, 37, 0.5);
box-sizing: border-box;
border-radius: 3px;
```
Fourm Like/Comment Button:
```
position: absolute;
left: 0%;
right: 0%;
top: 0%;
bottom: 0%;

background: #E5E5E5;
border: 1px solid rgba(37, 37, 37, 0.5);
box-sizing: border-box;
border-radius: 3px;
```
Fourm Comment:
```
position: absolute;
left: 0%;
right: 0%;
top: 62.58%;
bottom: 0%;
background: #C4C4C4;
border: 1px solid rgba(37, 37, 37, 0.5);
box-sizing: border-box;
border-radius: 3px;
```

**Comment by shelbyvjacobs** [comment]
This looks like it may be the parent of #80 Post component and #85 Comment component. Do you agree, @cjohnston96?
