### ISSUE TITLE
Component: Bio issue 

### ISSUE THREAD

**Issue by joshseven** [CotripperPlatform/CoTrip#92]
<img width="308" alt="Screen Shot 2019-12-06 at 2 48 52 PM" src="https://user-images.githubusercontent.com/40226464/70351720-8c0ab000-1837-11ea-9c13-332112042a40.png">

Location: 
Members Profile
Atoms:
Social icons

**Comment by sarahtsige** [comment]
@ZakkMan @Underwaterr   Looks like this component is done.  Let me know if if I'm ok to close or if there's something else that's needed on this.
