### ISSUE TITLE
Component: Molecular Previous Trips Card Issue

### ISSUE THREAD

**Issue by torykling** [CotripperPlatform/CoTrip#95]
![image](https://user-images.githubusercontent.com/55210397/70351925-fcb1cc80-1837-11ea-9299-391c31e900c9.png)

Location:
-Members Profile

Atom components:
-Slider
-Arrow

```
position: absolute;
width: 500px;
height: 275px;
left: 908px;
top: 725px;

background: #6A4C93;
box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 3px;
```

**Comment by TylerEikenberg** [comment]
Gonna take over working on this, doing the same thing with #60. I just need the image card from #82.
@wchrapcynski

**Comment by shelbyvjacobs** [comment]
Hey guys! Since Tyler is working on this on another issue, is it okay if I delete this one? That way there's a little less confusion.

**Comment by wchrapcynski** [comment]
> Hey guys! Since Tyler is working on this on another issue, is it okay if I delete this one? That way there's a little less confusion.

Make it so.

**Comment by bmillsmc** [comment]
closing this refer to #172
