### ISSUE TITLE
Component: Trip Header

### ISSUE THREAD

**Issue by stuvun** [CotripperPlatform/CoTrip#97]
**Location: Hawaii 2020**
![banner](https://user-images.githubusercontent.com/55634628/70352722-c7a67980-1839-11ea-8a3d-23ac92442e2d.png)
![travelBanner](https://user-images.githubusercontent.com/55634628/70352728-ca08d380-1839-11ea-862a-16a42b4fbd77.png)
**Props:**
* `location`

**Comments:**
Initially, I had these as two separate components, but I thought it would be more simple to combine these two as one component because they'd both be using the same prop. (The text would be the `location` prop and the image for the bottom half would be dictated by the `location` prop as well)

**Comment by MobolanleAdebesin** [comment]
Closing this issue as it is being addressed in issue #149
